"""
Preprocessing
"""
from pathlib import Path
import pandas as pd

# from utils.config import get_for_dataset, get_datasets_for_module, get_resource, set_defaults, \
#     get_input_file, get_input_file_wildcards
# from utils.misc import ifelse
from utils.environments import get_env
from utils.ModuleConfig import ModuleConfig


mcfg = ModuleConfig('preprocessing', config)
paramspace = mcfg.get_paramspace()


wildcard_constraints:
    dataset='\w+',


module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *

module preprocessing:
    snakefile: "rules.smk"
    config: config

# include: 'rules/preprocessing.smk'
include: 'rules/assemble.smk'
include: 'rules/plots.smk'


rule plots_all:
    input:
        mcfg.get_output_files(rules.plot_embedding.output),
        mcfg.get_output_files(rules.plot_umap.output),


rule all:
    input:
        mcfg.get_output_files(rules.assemble.output),
        rules.plots_all.input,
    default_target: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
