"""
Preprocessing
"""
from pathlib import Path
import pandas as pd

from utils.config import get_for_dataset, get_datasets_for_module, get_resource
from utils.misc import ifelse


module_name = 'preprocessing'
out_dir = Path(config['output_dir']) / module_name


wildcard_constraints:
    dataset='\w+',


module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *


include: 'rules/preprocessing.smk'
include: 'rules/assemble.smk'


rule all:
    input:
        # expand(rules.neighbors.output,dataset=get_datasets_for_module(config,module=module_name)),
        # expand(rules.umap.output,dataset=get_datasets_for_module(config,module=module_name)),
        expand(rules.assemble.output,dataset=get_datasets_for_module(config,module=module_name))
    default_target: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=config['images'] + f'/{module_name}',
            target='all'
        )
