include: 'rules/dependency_graph.smk'
include: 'rules/plots.smk'


rule test_barplot:
    input: expand(rules.barplot.output,out_dir='test/out/benchmark',metric=['s', 'max_uss', 'mean_load']),


rule test_swarmplot:
    input: expand(rules.swarmplot.output,out_dir='test/out/benchmark',metric=['score']),


rule test_embedding:
    input: expand(rules.embedding.output,filename='test/data/pbmc68k'),


rule test_umap:
    input: expand(rules.umap.output,filename='test/data/pbmc68k'),
