output_dir: test/out
images: test/images


DATASETS:
  test:
    input:
      qc:
        test: data/pbmc68k.h5ad
        test2: data/pbmc68k.h5ad
    qc:
      sample: batch
      donor: phase
      hue:
        - phase