"""
Clustering
"""
from pathlib import Path
from snakemake.utils import Paramspace

from utils.misc import all_but, unique_dataframe
from utils.config import get_hyperparams, get_resource, get_params_from_config, set_defaults, get_datasets_for_module, get_for_dataset
from utils.wildcards import expand_per, get_params, get_wildcards, wildcards_to_str
from utils.environments import get_env


module_name = 'clustering'
config = set_defaults(config,module_name)
out_dir = Path(config['output_dir']) / module_name
image_dir = Path(config['images']) / module_name


wildcard_constraints:
    dataset='((?![/]).)*',


module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *

module clustering:
    snakefile: "rules.smk"
    config: config

include: 'rules/clustering.smk'


rule all:
    input:
        expand(rules.clustering_merge.output,dataset=get_datasets_for_module(config,module=module_name)),
        expand(rules.clustering_plot_umap.output,dataset=get_datasets_for_module(config,module=module_name)),
    default_target: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=config['images'] + f'/{module_name}',
            target='all'
        )

