"""
Sample representations
"""
from pathlib import Path
import pandas as pd

from utils.environments import get_env
from utils.ModuleConfig import ModuleConfig

mcfg = ModuleConfig(
    module_name='sample_representation',
    config=config,
    config_params=[
        'sample_key',
        'cell_type_key',
        'use_rep',
        'n_epochs',
        'norm_counts',
        'raw_counts',
    ],
)
paramspace = mcfg.get_paramspace()

include: "rules/methods.smk"


rule all:
    input:
        mcfg.get_output_files(rules.pseudobulk.output),
        mcfg.get_output_files(rules.composition.output),
        mcfg.get_output_files(rules.cell_type_pseudobulk.output),
        mcfg.get_output_files(rules.pilot.output),
        mcfg.get_output_files(rules.scpoli.output),
        mcfg.get_output_files(rules.mrvi.output),
        mcfg.get_output_files(rules.gloscope.output),
        # mcfg.get_output_files(rules.scitd.output),
    default_target: True
    localrule: True


module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
    localrule: True
