from pathlib import Path
import pandas as pd

from utils.environments import get_env
from utils.ModuleConfig import ModuleConfig


mcfg = ModuleConfig(
    module_name='label_harmonization',
    config=config,
    config_params=['cellhint', 'organ'],
    wildcard_names=[],
    rename_config_params={'cellhint': 'module'},
)

paramspace = mcfg.get_paramspace()

include: 'rules/map_labels.smk'
include: 'rules/plots.smk'


rule all:
    input:
        mcfg.get_output_files(rules.cellhint.output),
        mcfg.get_output_files(rules.cellhint_plots.output),
        rules.plots_all.input,
    default_target: True
    localrule: True


module common:
    snakefile: "../common/Snakefile"
    config: config


use rule * from common as common_ *


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
    localrule: True
