"""
Exploration
"""
from pathlib import Path
import pandas as pd

from utils import get_resource


module_name = 'exploration'
dataset_df = pd.read_table(workflow.source_path(config['dataset_meta']),comment='#')
out_dir = Path(config['output_dir']) / module_name

wildcard_constraints:
    dataset='\w+',
    study='\w+',
    organ='\w+',


module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *


module preprocessing:
    snakefile: "../preprocessing/Snakefile"
    config: config

use rule * from preprocessing as preprocessing_*


module load_data:
    snakefile: "../load_data/Snakefile"
    config: config

use rule * from load_data as load_data_ *

include: 'rules/summary.smk'
include: 'rules/pseudobulk.smk'
include: 'rules/marker_genes.smk'
include: 'rules/qc.smk'
include: 'rules/barcode_matching.smk'
include: 'rules/batch_pcr.smk'


rule all:
    input:
        rules.summary_all.input,
        rules.pseudobulk_all.input,
        rules.marker_genes_all.input,
        rules.qc_all.input,
        rules.barcode_matching_all.input,
        rules.batch_pcr_all.input,
    default_target: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=config['images'] + f'/{module_name}',
            target='all'
        )
