# Note: relative paths must be relative to the project root, not the directory of the config file.
output_dir: data/out/scib-metrics

defaults:
  integration:
    unintegrated:
    combat:
    scvi:
      n_hidden: 128
      dispersion: gene
      max_epochs: 100
      use_observed_lib_size: true
    scanvi:
      n_hidden: 128
      dispersion: gene
      max_epochs: 100
      use_observed_lib_size: true
    scpoli:
      supervised: true
      early_stopping_kwargs:
        early_stopping_metric: val_prototype_loss
        mode: min
        threshold: 0
        patience: 20
        reduce_lr: true
        lr_patience: 13
        lr_factor: 0.1
  datasets:
    - lung
    # - pancreas
    # - pancreas_ari
    # - pancreas_nmi
    # - pancreas_asw
    # - pancreas_lisi

DATASETS:
  lung:
    input:
      integration: data/input/lung.h5ad
    label: cell_type
    batch: batch
    integration:
      unintegrated:
      # harmony:
    metrics:
      - ari
      - ari_leiden_y
      - ari_kmeans_y
      - nmi
      - nmi_leiden_y
      - nmi_kmeans_y
      - asw_label
      - asw_label_y
      - asw_batch
      - asw_batch_y
      - ilisi
      - ilisi_y
      - clisi
      - clisi_y
      - kbet_y
      - isolated_label_asw
      - isolated_label_asw_y
      - graph_connectivity
      - graph_connectivity_y
      - pcr
      - pcr_y

  pancreas:
    input:
      integration: data/input/pancreas.h5ad
    label: celltype
    batch: tech
    integration:
      unintegrated:
    metrics:
      - ari
      - ari_leiden_y
      - ari_kmeans_y
      - nmi
      - nmi_leiden_y
      - nmi_kmeans_y
      - asw_label
      - asw_label_y
      - asw_batch
      - asw_batch_y
      - ilisi
      - ilisi_y
      - clisi
      - clisi_y
  
  pancreas_ari:
    input:
      integration: data/input/pancreas.h5ad
    label: celltype
    batch: tech
    integration:
      unintegrated:
    metrics:
      - ari
      - ari_leiden_y
      - ari_kmeans_y
  
  pancreas_nmi:
    input:
      integration: data/input/pancreas.h5ad
    label: celltype
    batch: tech
    integration:
      unintegrated:
    metrics:
      - nmi
      - nmi_leiden_y
      - nmi_kmeans_y
  
  pancreas_asw:
    input:
      integration: data/input/pancreas.h5ad
    label: celltype
    batch: tech
    integration:
      unintegrated:
    metrics:
      - asw_label
      - asw_label_y
      - asw_batch
      - asw_batch_y
  
  pancreas_lisi:
    input:
      integration: data/input/pancreas.h5ad
    label: celltype
    batch: tech
    integration:
      unintegrated:
    metrics:
      - ilisi
      - ilisi_y
      - clisi
      - clisi_y
