"""
QC
"""
from pathlib import Path
import pandas as pd

from utils.ModuleConfig import ModuleConfig
from utils.environments import get_env


mcfg = ModuleConfig(
    module_name='qc',
    config=config,
    config_params=['sample', 'donor', 'batch', 'hue'],
)
params = mcfg.get_paramspace()

wildcard_constraints:
    dataset=r'[^/]+',
    file_id=r'[^/]+',

module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *

include: 'rules/qc.smk'
include: 'rules/doublets.smk'


rule all:
    input:
        rules.qc_metrics_all.input,
        rules.doublets_all.input,
    default_target: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
