# Note: relative paths must be relative to the project root, not the directory of the config file.

output_dir: data/out
images: images

output_map:
  relabel: data/out/label_harmonization/relabel/{dataset}.h5ad
  subset: data/out/subset/{dataset}/by_sample.h5ad
  preprocessing: data/out/preprocessing/{dataset}/neighbors.h5ad
  # integration: data/out/integration/dataset~{dataset}/method~{method}/batch~{batch},label~{label},hyperparams~{hyperparams},lineage_key~None/adata.h5ad
