# Note: relative paths must be relative to the project root, not the directory of the config file.

output_dir: data/out
images: images
use_gpu: true

output_map:
  relabel: data/out/relabel/{dataset}.zarr
  subset: data/out/subset/{dataset}/by_sample.h5ad
  pca: data/out/preprocessing/{dataset}/pca.h5ad
  neighbors: data/out/preprocessing/{dataset}/neighbors.h5ad
  preprocessing: data/out/preprocessing/{dataset}/preprocessed.zarr
  # integration: data/out/integration/dataset~{dataset}/method~{method}/batch~{batch},label~{label},hyperparams~{hyperparams},lineage_key~None/adata.h5ad
