"""
Data Subsetting for benchmark
"""
from pathlib import Path

from utils.environments import get_env
from utils.ModuleConfig import ModuleConfig

module_name = 'subset'
mcfg = ModuleConfig(module_name, config)
paramspace = mcfg.get_paramspace()

module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *

rule subset:
    input:
        lambda wildcards: mcfg.get_input_file(wildcards.dataset, wildcards.file_id),
    output:
        zarr=directory(mcfg.out_dir / paramspace.wildcard_pattern / '{strategy}.zarr')
    resources:
        mem_mb=mcfg.get_resource(profile='cpu',resource_key='mem_mb'),
        disk_mb=mcfg.get_resource(profile='cpu',resource_key='disk_mb'),
    params:
        n_cells=lambda wildcards: mcfg.get_for_dataset(wildcards.dataset, query=[module_name, 'n_cells']),
        sample_key=lambda wildcards: mcfg.get_for_dataset(wildcards.dataset, query=[module_name, 'sample']),
        label_key=lambda wildcards: mcfg.get_for_dataset(wildcards.dataset, query=[module_name, 'label']),
    conda:
        get_env(config, 'scanpy', env_dir='envs')
    script:
        'scripts/{wildcards.strategy}.py'


rule all:
    input:
        expand(
            expand(rules.subset.output, zip, **mcfg.get_input_file_wildcards(), allow_missing=True),
            strategy=['by_sample', 'within_sample']
        )
    default_target: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
