resources:
  cpu_merged:
    partition: cpu
    qos: normal
    gpu: 0
    mem_mb: 100000
    disk_mb: 50000
  cpu:
    partition: cpu
    qos: normal
    gpu: 0
    mem_mb: 100000
  gpu:
    partition: gpu
    qos: normal
    gpu: 1
    mem_mb: 100000

os: intel