defaults:
  datasets:
    - test_clustering
    - test_integration_clustering
  preprocessing:
    raw_counts: X
    assemble:
      - normalize
      - highly_variable_genes
      - pca
      - neighbors

DATASETS:
  test_clustering:
    input:
      preprocessing: data/pbmc68k.h5ad
      clustering: preprocessing
    preprocessing:
      label: bulk_labels
      batch: phase
      sample: phase
    clustering:
      neighbors_key: neighbors
      algorithm: leiden
      resolutions:
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8
  test_integration_clustering:
    input:
      preprocessing: data/pbmc68k.h5ad
      integration: preprocessing
      clustering: integration
    preprocessing:
      label: bulk_labels
      batch: phase
      sample: phase
    clustering:
      neighbors_key: neighbors
      algorithm: louvain
      resolutions:
        - 0.4
        - 0.8
    integration:
      raw_counts: raw/X
      norm_counts: layers/normcounts
      batch: phase
      label: louvain_0.4
      methods:
        unintegrated:
        combat:
      umap_colors:
        - louvain_0.4

