defaults:
  datasets:
    - test
  preprocessing:
    raw_counts: X
    norm_counts: normcounts
    batch: study
    lineage: lineage
    assemble:
      - counts
      - normalize
      - highly_variable_genes
      - pca
      - neighbors

DATASETS:
  test:
    input:
      preprocessing: data/pbmc68k.h5ad
      clustering: preprocessing
    preprocessing:
      label: bulk_labels
      batch: phase
      sample: phase
    clustering:
      neighbors_key: neighbors
      resolutions:
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8

