"""
Batch variable analysis with PC regression
"""
from pathlib import Path
import pandas as pd

from utils.config import get_resource, get_datasets_for_module, get_for_dataset, get_input_file, \
    get_input_file_per_dataset, get_input_file_wildcards
from utils.environments import get_env


module_name = 'batch_analysis'
out_dir = Path(config['output_dir']) / module_name
images_dir = Path(config['images']) / module_name
wildcard_pattern = '{dataset}/{file_id}'

input_files = get_input_file_wildcards(config, module_name)
out_dir.mkdir(parents=True, exist_ok=True)
pd.DataFrame(input_files).to_csv(out_dir / 'input_files.tsv', sep='\t', index=False)


wildcard_constraints:
    dataset='\w+',
    study='\w+',
    organ='\w+',


module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *


include: 'rules/batch_pcr.smk'
# TODO: add batch ingestion workflow


rule all:
    input:
        expand(rules.plot.output, zip, **input_files)
    default_target: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=config['images'] + f'/{module_name}',
            target='all'
        )
