"""
Batch variable analysis with PC regression
"""
from pathlib import Path
import pandas as pd

from utils.environments import get_env
from utils.ModuleConfig import ModuleConfig


mcfg = ModuleConfig(
    module_name='batch_analysis',
    config=config,
    config_params=['covariates', 'permute_covariates', 'n_permutations', 'sample_key'],
    wildcard_names=[],
)

paramspace = mcfg.get_paramspace()


wildcard_constraints:
    dataset='\w+',
    study='\w+',
    organ='\w+',


module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *


include: 'rules/batch_pcr.smk'
# TODO: add batch ingestion workflow


rule all:
    input:
        mcfg.get_output_files(rules.collect.output),
        mcfg.get_output_files(rules.plot.output),
    default_target: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
