cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --gpus={resources.gpu}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/%j-{rule}-{wildcards}.out
    --error=logs/{rule}/%j-{rule}-{wildcards}.err
    --parsable
default-resources:
  - partition=cpu
  - gpu=0
  - mem_mb=32000
  - disk_mb=20000
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 30
jobs: 40
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-cancel: scancel
rerun-triggers:
  - mtime
  - params
  - input
  - software-env
  - code
show-failed-logs: True
#shadow-prefix: /hpc/projects/data_lg/michaela.mueller/scratch
shadow-prefix: /tmp/michaela.mueller
latency-wait: 90
configfile: configs/optional/comp_czbiohub.yaml
