defaults:
  integration:
    unintegrated:
    bbknn:
    harmony:
    scgen:
      max_epochs: 50
      batch_size: 32
      early_stopping: True
      early_stopping_patience: 25
    scvi:
      n_hidden: 128
      dispersion:
        - gene
        #- gene-batch
        #- gene-label
        #- gene-cell
      max_epochs: 10
      use_observed_lib_size: true
    scanvi:
      n_hidden: 128
      dispersion: gene
      max_epochs: 10
      use_observed_lib_size: true
    scpoli:
      supervised: true
      early_stopping_kwargs:
        early_stopping_metric: val_prototype_loss
        mode: min
        threshold: 0
        patience: 20
        reduce_lr: true
        lr_patience: 13
        lr_factor: 0.1
  
  metrics:
    - nmi
    - ari
    - asw_label
    - asw_batch
    - cell_cycle
    - clisi
    - ilisi
    - graph_connectivity
    - isolated_label_asw
    - isolated_label_f1
    - pcr
  datasets:
    - blood_benchmark
    - test
  subset:
    n_cells: 500000

output_map:
  subset: data/out/subset/{dataset}/by_sample.zarr
  preprocessing: data/out/preprocessing/{dataset}/neighbors.zarr

DATASETS:
  blood_benchmark:
    input:
      subset: data/out/load_data/merged/subset/blood-benchmark.zarr
      preprocessing: subset
      integration: preprocessing
    label: cell_type
    batch: study
    sample: sample
    metrics:
      - nmi
      - ari
      - asw_label
      - asw_batch
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_asw
      - isolated_label_f1
      - pcr
  test:
    input:
      subset: data/pbmc68k.h5ad
      preprocessing: subset
      integration: preprocessing
    label: bulk_labels
    batch: phase
    sample: phase
    metrics:
      - nmi
      - ari
      - asw_label
      - asw_batch
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_asw
      - isolated_label_f1
      - pcr
