defaults:
  integration:
    scvi:
      n_hidden: 128
      dispersion:
        - gene
        #- gene-batch
        #- gene-label
        #- gene-cell
      max_epochs: 10
      use_observed_lib_size: true
    scanvi:
      n_hidden: 128
      dispersion: gene
      max_epochs: 10
      use_observed_lib_size: true
    combat:
    scanorama:
    unintegrated:
  metrics:
    - nmi
    - ari
    - asw_label
    - asw_batch
    - cell_cycle
    - clisi
    - ilisi
    - graph_connectivity
    - isolated_label_asw
    - isolated_label_f1
    - pcr
  datasets:
    - test

DATASETS:
  test:
    label: bulk_labels
    batch: phase
    adata_file: 'data/pbmc68k.h5ad'
    metrics:
      - nmi
      - ari
      - asw_label
      - asw_batch
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_asw
      - isolated_label_f1
      - pcr
  test2:
    label: bulk_labels
    batch: phase
    adata_file: 'data/pbmc68k.h5ad'
    metrics:
      - nmi
      - ari
      - asw_label
      - asw_batch
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_asw
      - isolated_label_f1
      - pcr
