# Note: relative paths must be relative to the project root, not the directory of the config file.

output_dir: data/out
dataset_meta: configs/datasets.tsv

defaults:
  datasets:
    - pancreas

DATASETS:
  pancreas:
    adata_file: data/pancreas.h5ad
    label: celltype
    batch: tech
    metrics:
      - ari
      - ari_leiden_y
      - ari_kmeans_y
      - nmi
      - nmi_leiden_y
      - nmi_kmeans_y
      - asw_label
      - asw_label_y
      - asw_batch
      - asw_batch_y
      - ilisi
      - ilisi_y
      - clisi
      - clisi_y
  integration:
    scvi:
      n_hidden: 128
      dispersion: gene
      max_epochs: 100
      use_observed_lib_size: true
    scanvi:
      n_hidden: 128
      dispersion: gene
      max_epochs: 100
      use_observed_lib_size: true
    combat:
    unintegrated:
