# Note: relative paths must be relative to the project root, not the directory of the config file.

output_dir: data/out
dataset_meta: configs/datasets.tsv

defaults:
  integration:
    - scvi
    - scanvi
    - combat
    - scanorama
    - unintegrated
  metrics:
    - nmi
    - ari
    - asw_label
    - asw_batch
    - cell_cycle
    - clisi
    - ilisi
    - graph_connectivity
    - isolated_label_asw
    - isolated_label_f1
    - pcr
  datasets:
    - pancreas

DATASETS:
  pancreas:
    adata_file: 'data/pancreas.h5ad'
    label: celltype
    batch: tech
    metrics:
      - ari
      - ari_leiden_y
        #- ari_kmeans_y
      - nmi
      - nmi_leiden_y
        #- nmi_kmeans_y
  #    - asw_label
  #    - asw_label_y
  #    - asw_batch
  #    - asw_batch_y
      - ilisi
      - ilisi_y
      - clisi
      - clisi_y
