# Note: relative paths must be relative to the project root, not the directory of the config file.

output_dir: data/out
dataset_meta: configs/datasets.tsv

input:
  metrics: data/out/integration/{dataset}/{method}.h5ad

resources:
  cpu:
    partition: cpu_p
    qos: icb
  gpu:
    partition: gpu_p
    qos: gpu

defaults:
  integration:
    - scvi
    - scanvi
    - combat
    - scanorama
    - unintegrated
  metrics:
    - nmi
    - ari
    - asw_label
    - asw_batch
    - cell_cycle
    - clisi
    - ilisi
    - graph_connectivity
    - isolated_label_asw
    - isolated_label_f1
    - pcr
  datasets:
    - pancreas_ari_nmi
    - pancreas_lisi

DATASETS:
  pancreas_ari_nmi:
    adata_file: 'data/pancreas.h5ad'
    label: celltype
    batch: tech
    metrics:
      - ari
      - ari_leiden_y
      - ari_kmeans_y
      - nmi
      - nmi_leiden_y
      - nmi_kmeans_y
  pancreas_asw:
    adata_file: 'data/pancreas.h5ad'
    label: celltype
    batch: tech
    metrics:
      - asw_label
      - asw_label_y
      - asw_batch
      - asw_batch_y
  pancreas_lisi:
    adata_file: 'data/pancreas.h5ad'
    label: celltype
    batch: tech
    metrics:
      - ilisi
      - ilisi_y
      - clisi
      - clisi_y
