defaults:
  integration:
    unintegrated:
    bbknn:
    harmony:
    scgen:
      max_epochs: 50
      batch_size: 32
      early_stopping: True
      early_stopping_patience: 25
    scvi:
      n_hidden: 128
      dispersion:
        - gene
        #- gene-batch
        #- gene-label
        #- gene-cell
      max_epochs: 10
      use_observed_lib_size: true
    scanvi:
      n_hidden: 128
      dispersion: gene
      max_epochs: 10
      use_observed_lib_size: true
    scpoli:
      supervised: true
      early_stopping_kwargs:
        early_stopping_metric: val_prototype_loss
        mode: min
        threshold: 0
        patience: 20
        reduce_lr: true
        lr_patience: 13
        lr_factor: 0.1
  metrics:
    - nmi_leiden_y
    - ari_leiden_y
    - asw_label_y
    - asw_batch_y
    - cell_cycle
    # - clisi_y
    # - ilisi_y
    - graph_connectivity
    - isolated_label_asw
    # - isolated_label_f1
    - pcr
  datasets:
    - blood_benchmark
    # - blood_benchmark_donor
    # - test
  subset:
    n_cells: 500000

output_map:
  label_harmonization: data/out/label_harmonization/remap_labels/{dataset}.zarr
  subset: data/out/subset/{dataset}/by_sample.zarr
  preprocessing: data/out/preprocessing/{dataset}/neighbors.zarr

DATASETS:
  blood_benchmark:
    input:
      label_harmonization: data/out/load_data/merged/subset/blood-benchmark.zarr
      subset: label_harmonization
      preprocessing: subset
      integration: preprocessing
    label_harmonization:
      mapping:
        file: data/input/label_harmonization/mapping_coarse.tsv
        order:
          - cell_type
          - harmonized_label
          - lineage
    label: harmonized_label
    batch: study
    sample: sample
    lineage: lineage
  blood_benchmark_donor:
    input:
      integration: data/out/preprocessing/blood_benchmark/neighbors.zarr
    label: cell_type
    batch: donor
    sample: sample
  test:
    input:
      subset: data/pbmc68k.h5ad
      preprocessing: subset
      integration: preprocessing
    label: bulk_labels
    batch: phase
    sample: phase
    metrics:
      - nmi
      - ari
      - asw_label
      - asw_batch
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_asw
      - isolated_label_f1
      - pcr
