# Note: relative paths must be relative to the project root, not the directory of the config file.

output_dir: data/out
images: images

defaults:
  datasets:
    - test
    - blood

resources:
  cpu_merged:
    partition: cpu_p
    qos: icb
    gpu: 0
    mem_mb: 500000
    disk_mb: 150000
  cpu:
    partition: cpu_p
    qos: icb
    gpu: 0
    mem_mb: 300000
  gpu:
    partition: gpu_p
    qos: gpu
    gpu: 1
    mem_mb: 90000
