# Note: relative paths must be relative to the project root, not the directory of the config file.

output_dir: data/out
images: images

resources:
  cpu_merged:
    partition: cpu
    qos: normal
    gpu: 0
    mem_mb: 500000
    disk_mb: 150000
  cpu:
    partition: cpu
    qos: normal
    gpu: 0
    mem_mb: 200000
  gpu:
    partition: gpu
    qos: normal
    gpu: 1
    mem_mb: 200000
