# Note: relative paths must be relative to the project root, not the directory of the config file.

output_dir: data/out
images: images
use_gpu: true

output_map:
  relabel: data/out/relabel/dataset~{dataset}/file_id~{file_id}.zarr
  subset: data/out/subset/dataset~{dataset}/file_id~{file_id}/by_sample.zarr
  pca: data/out/preprocessing/dataset~{dataset}/file_id~{file_id}/pca.zarr
  neighbors: data/out/preprocessing/dataset~{dataset}/file_id~{file_id}/neighbors.zarr
  preprocessing: data/out/preprocessing/dataset~{dataset}/file_id~{file_id}/preprocessed.zarr
  integration: data/out/integration/dataset~{dataset}/file_id~{file_id}/method~{method}/label~{label}/batch~{batch}/hyperparams~{hyperparams}/postprocessed.zarr
