# Note: relative paths must be relative to the project root, not the directory of the config file.

output_dir: data/out
dataset_meta: configs/datasets.tsv

defaults:
  integration:
    unintegrated:
    combat:
    scvi:
      n_hidden: 128
      dispersion: gene
      max_epochs: 100
      use_observed_lib_size: true
    scanvi:
      n_hidden: 128
      dispersion: gene
      max_epochs: 100
      use_observed_lib_size: true
    scpoli:
      supervised: true
      early_stopping_kwargs:
        early_stopping_metric: val_prototype_loss
        mode: min
        threshold: 0
        patience: 20
        reduce_lr: true
        lr_patience: 13
        lr_factor: 0.1
  datasets:
    - pancreas
    #- pancreas_ari
    #- pancreas_nmi
    #- pancreas_asw
    #- pancreas_lisi

DATASETS:
  pancreas:
    input:
    adata_file: data/pancreas.h5ad
    label: celltype
    batch: tech
  pancreas_ari:
    input:
    adata_file: data/pancreas.h5ad
    label: celltype
    batch: tech
    metrics:
      - ari
      - ari_leiden_y
      - ari_kmeans_y
  pancreas_nmi:
    input:
    adata_file: data/pancreas.h5ad
    label: celltype
    batch: tech
    metrics:
      - nmi
      - nmi_leiden_y
      - nmi_kmeans_y
  pancreas_asw:
    input:
    adata_file: data/pancreas.h5ad
    label: celltype
    batch: tech
    metrics:
      - asw_label
      - asw_label_y
      - asw_batch
      - asw_batch_y
  pancreas_lisi:
    input:
    adata_file: data/pancreas.h5ad
    label: celltype
    batch: tech
    metrics:
      - ilisi
      - ilisi_y
      - clisi
      - clisi_y
