defaults:
  datasets:
    - test
    - test2
  integration:
    raw_counts: raw/X
    norm_counts: layers/normcounts
    methods:
      unintegrated:
      bbknn:
      combat:
      harmony:
      scanorama:
      scgen:
        max_epochs: 10
      scvi:
        n_latent: 30
        n_hidden: 128
        dispersion:
          - gene
          #- gene-batch
          #- gene-label
          #- gene-cell
        # scArches params
        use_layer_norm: both
        use_batch_norm: none
        encode_covariates: True
        dropout_rate: 0.2
        n_layers: 2
        # training params
        max_epochs: 10
        use_observed_lib_size: true
      scanvi:
        n_latent: 30
        n_hidden: 128
        dispersion: gene
        # scArches params
        use_layer_norm: both
        use_batch_norm: none
        encode_covariates: True
        dropout_rate: 0.2
        n_layers: 2
        # training params
        max_epochs: 10
        use_observed_lib_size: true
        # n_samples_per_label: 100
      scpoli:
        supervised:
          - true
          - false
        model:
          embedding_dims: 30
          recon_loss: nb
          latent_dim: 100
          # hidden_layer_sizes: [512, 512]
        train:
          n_epochs: 10
          eta: 5
  metrics:
    methods:
      - nmi_leiden_y
      - ari_leiden_y
      - asw_label
      - asw_batch
      - cell_cycle
      - clisi_y
      - ilisi_y
      - graph_connectivity
      - isolated_label_asw_y
      - pcr
      - kbet_y
      - nmi
      - ari
      - asw_label
      - asw_batch
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_asw
      - isolated_label_f1
  preprocessing:
    raw_counts: X
    batch: study
    assemble:
      - counts
      - normalize
      - highly_variable_genes
      - pca
      - neighbors

DATASETS:
  test:
    input:
      subset:
        test_data: data/pbmc68k.h5ad
        test_data2: data/pbmc68k.h5ad
      preprocessing: subset
      integration: preprocessing
      metrics: integration
    subset:
      label: bulk_labels
      sample: phase
      n_cells: 1000
    preprocessing:
      label: bulk_labels
      batch: phase
      highly_variable_genes: false
    integration:
      label: bulk_labels
      batch: phase
    metrics:
      label: bulk_labels
      batch: phase
      unintegrated: layers/norm_counts
      corrected: X

  test2:
    input:
      split_data: data/pbmc68k.h5ad
      preprocessing: split_data
      integration: preprocessing
      metrics: integration
    split_data:
      key: phase
      values:
        - G1
        - S
    preprocessing:
      raw_counts: X
      assemble:
        - counts
        - normalize
        - highly_variable_genes
        - pca
        - neighbors
    integration:
      label: bulk_labels
      batch: batch
      umap_colors:
        - bulk_labels
        - phase
    metrics:
      label: bulk_labels
      batch: phase
      unintegrated: layers/norm_counts
      corrected: X
