"""
QC
"""
from pathlib import Path
import pandas as pd

from utils.ModuleConfig import ModuleConfig
from utils.environments import get_env


mcfg = ModuleConfig(
    module_name='doublets',
    config=config,
    config_params=[
        'counts',
        'batch'
    ],
    rename_config_params={'batch': 'batch_key'}
)
params = mcfg.get_paramspace()

wildcard_constraints:
    dataset=r'[^/]+',
    file_id=r'[^/]+',

module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *

include: 'rules/doublets.smk'


rule all:
    input:
        mcfg.get_output_files(rules.collect.output),
    default_target: True
    localrule: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
    localrule: True
