resources:
  cpu_merged:
    partition: cpu_p
    qos: icb
    gpu: 0
    mem_mb: 100000
    disk_mb: 50000
  cpu:
    partition: cpu_p
    qos: cpu_normal
    gpu: 0
    mem_mb: 50000
  gpu:
    partition: gpu_p
    qos: gpu_normal
    gpu: 1
    mem_mb: 90000

os: intel
