defaults:
  datasets:
    - gut_ref
#    - gut
  preprocessing:
    raw_counts: X
    norm_counts: normcounts
    batch: batch
    #lineage: lineage
    assemble:
      - counts
      - normalize
      - highly_variable_genes
      - pca
      - neighbors
  integration:
    label: level_3_annot
    batch: batch
    raw_counts: X
    norm_counts: normcounts
    methods:
      unintegrated:
      bbknn:
      combat:
      harmony:
      #scanorama:
      #scgen:
      #  max_epochs: 50
      scvi:
        n_hidden: 128
        dispersion:
          - gene
          - gene-batch
          - gene-label
          - gene-cell
        max_epochs: 35
        use_observed_lib_size: true
      scanvi:
        n_hidden: 128
        dispersion: gene
        max_epochs: 30
        use_observed_lib_size: true
      scpoli:
        supervised:
          - true
          - false
        model:
          embedding_dims: 5
          recon_loss: nb
          # latent_dim: 30
          # hidden_layer_sizes: [512, 512]
        train:
          n_epochs: 30
          eta: 5
    umap_colors:
      - level_3_annot
      - batch
      - sex
      - technology
      - study
      - disease
      
  metrics:
    label: level_3_annot
    batch: batch
    methods:
      - nmi_leiden_y
      - ari_leiden_y
      - asw_label
      - asw_batch
      # - cell_cycle
      #- clisi_y
      #- ilisi_y
      - graph_connectivity
      # - isolated_label_asw_y
      # - isolated_label_f1_y
      - pcr
      #- kbet_y


DATASETS: 

  gut_ref:
    input:
      preprocessing: data/gut_ref.zarr
      integration: preprocessing
    preprocessing:
      raw_counts: X
      highly_variable_genes:
        n_top_genes: 4000
      assemble:
        - counts
        - normalize
        - highly_variable_genes
        - pca
        - neighbors
    integration:
      label: level_3_annot
      batch: batch
      #lineage: lineage
    metrics:
      label: level_3_annot
      batch: batch
      #lineage: lineage

#  gut_test:
#    input:
#      subset: data/out/load_data/merged/organ/gut.zarr
#      preprocessing: subset
#      integration: preprocessing
#    subset:
#      label: cell_type
#      sample: sample
#      n_cells: 20000
#    preprocessing:
#      raw_counts: X
#      highly_variable_genes:
#        n_top_genes: 2000
#      assemble:
#        - counts
#        - normalize
#        - highly_variable_genes
#        - pca
#        - neighbors
#    integration:
#      label: cell_type
#      batch: batch
#      #lineage: lineage
#    metrics:
#      label: cell_type
#      batch: batch
#      #lineage: lineage