defaults:
  integration:
    norm_counts: normcounts
    raw_counts: X
    methods:
      unintegrated:
      bbknn:
      harmony:
      scgen:
        max_epochs: 50
        batch_size: 32
        early_stopping: True
        early_stopping_patience: 25
      scvi:
        n_hidden: 128
        dispersion:
          - gene
          #- gene-batch
          #- gene-label
          #- gene-cell
        max_epochs: 10
        use_observed_lib_size: true
      scanvi:
        n_hidden: 128
        dispersion: gene
        max_epochs: 10
        use_observed_lib_size: true
      scpoli:
        supervised: true
        early_stopping_kwargs:
          early_stopping_metric: val_prototype_loss
          mode: min
          threshold: 0
          patience: 20
          reduce_lr: true
          lr_patience: 13
          lr_factor: 0.1
  metrics:
    methods:
      - nmi_leiden_y
      - ari_leiden_y
      - asw_label_y
      - asw_batch_y
      - cell_cycle
      - clisi_y
      - ilisi_y
      - graph_connectivity
      - isolated_label_asw
      - isolated_label_asw_y
      - isolated_label_f1_y
      - pcr
      - kbet_y
  datasets:
    - blood_benchmark_test
    # - blood_lineage_specific
    # - blood_benchmark_donor
    # - test
  # subset:
  #   n_cells: 1000000
  preprocessing:
    raw_counts: X
    batch: study
    lineage: lineage
    assemble:
      - counts
      - normalize
      - pca
      - neighbors

DATASETS:

  blood_benchmark_test:
    input:
      subset: data/out/relabel/blood_benchmark.h5ad
      preprocessing: subset
      integration: preprocessing
    subset:
      label: harmonized_label
      sample: sample
      n_cells: 1000
    preprocessing:
      raw_counts: X
      assemble:
        - counts
        - normalize
        - pca
        - neighbors
    integration:
      label: harmonized_label
      batch: study
    metrics:
      label: harmonized_label
      batch: study

  blood_benchmark:
    input:
      relabel: data/out/load_data/merged/subset/blood-benchmark.zarr
      # subset: relabel
      preprocessing: relabel
      integration: preprocessing
    relabel:
      mapping:
        file: data/input/label_harmonization/mapping_coarse.tsv
        order:
          - cell_type
          - harmonized_label
          - lineage
          - lineage_coarse
    integration:
      label: harmonized_label
      batch: study
    metrics:
      label: harmonized_label
      batch: study

  blood_benchmark_donor:
    input:
      integration: data/out/preprocessing/blood_benchmark/neighbors.h5ad
    integration:
      label: cell_type
      batch: donor
      sample: sample

  blood_lineage_specific:
    input:
      integration: data/out/preprocessing/blood_benchmark/neighbors.h5ad
    integration:
      label: harmonized_label
      batch: study
      sample: sample
      lineage: lineage
    # methods:
    #   unintegrated:
    #   scvi:
    #     n_hidden: 128
    #     dispersion: gene
    #     max_epochs: 10
    #     use_observed_lib_size: true

  test:
    input:
      subset: data/pbmc68k.h5ad
      preprocessing: subset
      integration: preprocessing
    subset:
      label: bulk_labels
      sample: phase
    preprocessing:
      label: bulk_labels
      batch: phase
      sample: phase
    integration:
      label: bulk_labels
      batch: phase
    metrics:
      methods:
        - nmi
        - ari
        - asw_label
        - asw_batch
        - clisi
        - ilisi
        - graph_connectivity
        - isolated_label_asw
        - isolated_label_f1
        - pcr
