defaults:
  datasets:
    - gut
    # - blood_benchmark
    # - blood_benchmark_donor
    # - test
  integration:
    label: cell_type
    batch: batch
    raw_counts: X
    norm_counts: normcounts
    methods:
      unintegrated:
      bbknn:
      combat:
      harmony:
      scanorama:
      # scgen:
      #   max_epochs: 50
      scvi:
        n_hidden: 128
        dispersion:
          - gene
          #- gene-batch
          #- gene-label
          #- gene-cell
        max_epochs: 10
        use_observed_lib_size: true
      scanvi:
        n_hidden: 128
        dispersion: gene
        max_epochs: 10
        use_observed_lib_size: true
      scpoli:
        supervised:
          - true
          - false
        model:
          embedding_dims: 5
          recon_loss: nb
          # latent_dim: 30
          # hidden_layer_sizes: [512, 512]
        train:
          n_epochs: 20
          eta: 5
    umap_colors:
      - cell_type
      - batch
      - sex
      - assay
      - study
      - disease
      
  metrics:
    label: cell_type
    batch: batch
    methods:
      - nmi_leiden_y
      - ari_leiden_y
      - asw_label
      - asw_batch
      # - cell_cycle
      # - clisi_y
      # - ilisi_y
      - graph_connectivity
      # - isolated_label_asw_y
      # - isolated_label_f1_y
      - pcr
      # - kbet_y
  # subset:
  #   n_cells: 1000000
  preprocessing:
    raw_counts: X
    norm_counts: normcounts
    batch: batch
    #lineage: lineage
    assemble:
      - counts
      - normalize
      - highly_variable_genes
      - pca
      - neighbors

DATASETS: 

  gut:
    input:
      subset: data/out/load_data/merged/organ/gut.zarr
      preprocessing: subset
      integration: preprocessing
    subset:
      label: cell_type
      sample: sample
      n_cells: 200000
    preprocessing:
      raw_counts: X
      highly_variable_genes:
        n_top_genes: 4000
      assemble:
        - counts
        - normalize
        - highly_variable_genes
        - pca
        - neighbors
    integration:
      label: cell_type
      batch: batch
      #lineage: lineage
    metrics:
      label: cell_type
      batch: batch
      #lineage: lineage