defaults:
  integration:
    raw_counts: counts
    norm_counts: normcounts
    methods:
      unintegrated:
      # bbknn:
      # combat:
      harmony:
      scanorama:
      scgen:
        max_epochs: 50
      scvi:
        n_hidden: 128
        dispersion:
          - gene
          #- gene-batch
          #- gene-label
          #- gene-cell
        max_epochs: 10
        use_observed_lib_size: true
      scanvi:
        n_hidden: 128
        dispersion: gene
        max_epochs: 10
        use_observed_lib_size: true
      scpoli:
        supervised:
          - true
          - false
        model:
          latent_dim: 30
          embedding_dims: 10
          # hidden_layer_sizes: [512, 512]
          recon_loss: nb
        train:
          n_epochs: 50
          eta: 10

  metrics:
    methods:
      - nmi_leiden_y
      - ari_leiden_y
      - asw_label_y
      - asw_batch_y
      - cell_cycle
      - clisi_y
      - ilisi_y
      - graph_connectivity
      - isolated_label_asw
      - isolated_label_asw_y
      - isolated_label_f1_y
      - pcr
      - kbet_y
  datasets:
    - blood_benchmark_test
    - blood_benchmark
    # - blood_benchmark_donor
    # - test
  # subset:
  #   n_cells: 1000000
  preprocessing:
    raw_counts: X
    norm_counts: normcounts
    batch: study
    lineage: lineage
    assemble:
      - counts
      - normalize
      - highly_variable_genes
      - pca
      - neighbors

DATASETS:

  blood_benchmark_test:
    input:
      subset: data/out/relabel/blood_benchmark.h5ad
      preprocessing: subset
      integration: preprocessing
    subset:
      label: harmonized_label
      sample: sample
      n_cells: 10000
    preprocessing:
      raw_counts: X
      norm_counts: normcounts
      highly_variable_genes:
        n_top_genes: 3000
      assemble:
        - counts
        - normalize
        - highly_variable_genes
        - pca
        - neighbors
    integration:
      label: author_annotation
      batch: sample
      lineage: lineage
    metrics:
      label: author_annotation
      batch: sample
      lineage: lineage

  blood_benchmark:
    input:
      relabel: data/out/load_data/merged/subset/blood-benchmark.zarr
      # subset: relabel
      preprocessing: relabel
      integration: preprocessing
    relabel:
      mapping:
        file: data/input/label_harmonization/mapping_coarse.tsv
        order:
          - cell_type
          - harmonized_label
          - lineage
          - lineage_coarse
    preprocessing:
      raw_counts: X
      norm_counts: normcounts
      highly_variable_genes:
        n_top_genes: 3000
      assemble:
        - counts
        - normalize
        - highly_variable_genes
        - pca
        - neighbors
    integration:
      label: author_annotation
      batch: study
      lineage: lineage
      umap_colors:
        - harmonized_label
        - donor
        - lineage
    metrics:
      label: author_annotation
      batch: study
      lineage: lineage

  blood_benchmark_donor:
    input:
      integration: data/out/preprocessing/blood_benchmark/neighbors.h5ad
    integration:
      label: cell_type
      batch: donor
      sample: sample

  blood_lineage_specific:
    input:
      integration: data/out/preprocessing/blood_benchmark/neighbors.h5ad
    integration:
      label: harmonized_label
      batch: study
      sample: sample
      lineage: lineage
    # methods:
    #   unintegrated:
    #   scvi:
    #     n_hidden: 128
    #     dispersion: gene
    #     max_epochs: 10
    #     use_observed_lib_size: true

  test:
    input:
      subset: data/pbmc68k.h5ad
      preprocessing: subset
      integration: preprocessing
    subset:
      label: bulk_labels
      sample: phase
    preprocessing:
      label: bulk_labels
      batch: phase
      sample: phase
    integration:
      label: bulk_labels
      batch: phase
    metrics:
      methods:
        - nmi
        - ari
        - asw_label
        - asw_batch
        - clisi
        - ilisi
        - graph_connectivity
        - isolated_label_asw
        - isolated_label_f1
        - pcr
