defaults:
  datasets:
    - gut
    # - blood_benchmark
    # - blood_benchmark_donor
    # - test
  integration:
    raw_counts: counts
    norm_counts: normcounts
    methods:
      unintegrated:
      bbknn:
      combat:
      harmony:
      scanorama:
      # scgen:
      #   max_epochs: 50
      scvi:
        n_hidden: 128
        dispersion:
          - gene
          #- gene-batch
          #- gene-label
          #- gene-cell
        max_epochs: 10
        use_observed_lib_size: true
      scanvi:
        n_hidden: 128
        dispersion: gene
        max_epochs: 10
        use_observed_lib_size: true
      scpoli:
        supervised:
          - true
          - false
        model:
          embedding_dims: 5
          recon_loss: nb
          # latent_dim: 30
          # hidden_layer_sizes: [512, 512]
        train:
          n_epochs: 20
          eta: 5

  metrics:
    methods:
      - nmi_leiden_y
      - ari_leiden_y
      - asw_label
      - asw_batch
      # - cell_cycle
      # - clisi_y
      # - ilisi_y
      - graph_connectivity
      # - isolated_label_asw_y
      # - isolated_label_f1_y
      - pcr
      # - kbet_y
  # subset:
  #   n_cells: 1000000
  preprocessing:
    raw_counts: counts
    norm_counts: normcounts
    batch: sourceID
    #lineage: lineage
    assemble:
      - counts
      - normalize
      - highly_variable_genes
      - pca
      - neighbors

DATASETS: 

  gut:
    input:
      preprocessing: data/out/load_data/merged/organ/gut.zarr
      integration: preprocessing
      label: level_3_annot
      batch: sourceID
      sample: sampleID