from pathlib import Path
import pandas as pd

from utils.config import get_datasets_for_module, get_for_dataset, get_resource, get_wildcards_from_config, set_defaults
from utils.wildcards import get_params, get_wildcards
from utils.misc import unlist_dict, unpack_dict_in_df


module_name = 'relabel'
config = set_defaults(config,module_name,warn=False)
out_dir = Path(config['output_dir']) / module_name


rule relabel:
    input:
        anndata=lambda wildcards: get_for_dataset(config, wildcards.dataset, query=['input', module_name]),
        mapping=lambda wildcards: get_for_dataset(config, wildcards.dataset, query=[module_name, 'mapping', 'file'])
    output:
        zarr=directory(out_dir / '{dataset}.zarr'),
    params:
        mapping_order=lambda wildcards: get_for_dataset(config, wildcards.dataset, query=[module_name, 'mapping', 'order']),
    conda:
        'envs/scanpy.yaml'
    resources:
        partition=lambda w: get_resource(config,resource_key='partition'),
        qos=lambda w: get_resource(config,resource_key='qos'),
        mem_mb=lambda w: get_resource(config,resource_key='mem_mb'),
    script:
        'script.py'


rule relabel_all:
    input:
        expand(
            rules.relabel.output,
            dataset=get_datasets_for_module(config, module_name).keys()
        )


rule all:
    input:
        rules.relabel_all.input
    default_target: True


module common:
    snakefile: "../common/Snakefile"
    config: config


use rule * from common as common_ *


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=config['images'] + f'/{module_name}',
            target='all'
        )